name: Update Changelog

on:
  release:
    types: [published]

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv
    - name: Update Changelog
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python update_changelog.py
    - name: Commit changes
      run: |
        set -x  # Enable verbose output

        echo "Configuring Git..."
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        echo "GitHub event name: ${{ github.event_name }}"
        echo "GitHub head ref: ${{ github.head_ref }}"
        echo "GitHub ref name: ${{ github.ref_name }}"

        echo "Fetching latest changes..."
        git fetch origin

        echo "Checking out and updating branch..."
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          git checkout -B "${{ github.head_ref }}" "origin/${{ github.head_ref }}"
          git pull origin "${{ github.head_ref }}"
        else
          git checkout -B "${{ github.ref_name }}" "origin/${{ github.ref_name }}"
          git pull origin "${{ github.ref_name }}"
        fi

        echo "Current branch after checkout:"
        git branch

        echo "Running update script..."
        python update_changelog.py

        echo "Checking for changes..."
        git add docs/changelog.md
        git pull
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          echo "Changes detected, committing..."
          git commit -m "Update changelog for latest release"
          echo "Pushing changes..."
          git push origin HEAD:"${{ github.head_ref || github.ref_name }}" || echo "Failed to push changes"
        fi

        echo "Final Git status:"
        git status
